# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Publish

on:
  workflow_run:
    workflows: [ "Gradle Build" ]
    branches: [ main ]
    types:
      - completed
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#    types: [ closed ]    
#  release:
#    types: [created]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The triggering workflow passed"
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "The triggering workflow failed"
  
  merge_completed:
    needs: on-success
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Display PR Number
      run: |
        echo "PR #${{ github.event.number }} has been merged"

    - name: Download Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: artifact
        path: ${{ github.workspace }}}/app/artifact

    - name: Output Gradle VersionName
      working-directory : ${{ github.workspace }}/app/artifact
      run : |
        echo "Output Gradle VersionName"
        echo "${{env.VERSIONNAME}}"
      
    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog
      env:
        REPO: ${{ github.repository }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        artifacts: HideMockLocation.apk
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false
  
  merge_closed:
    needs: on-success
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    
    steps:
    - name: PR Closed Without Merge
      run: |
        echo "PR #${{ github.event.number }} has been closed without being merged"
