# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
 #   - uses: actions/checkout@v2
 #   - name: Set up JDK 11
 #     uses: actions/setup-java@v2
 #     with:
 #       java-version: '11'
 #       distribution: 'temurin'
 #       server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
 #       settings-path: ${{ github.workspace }} # location for the settings.xml file

#    - name: Build with Gradle
#      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
#      with:
#        arguments: build
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: HideMockLocation.apk
        path: ${{ github.workspace }}}/app/artifact

    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog
      env:
        REPO: ${{ github.repository }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false
